name: CI
on:
  push: { branches: [ "main" ] }
  pull_request: {}
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Tests
        run: pytest -q --cov=app --cov-report=term-missing

      - name: Build Docker (local check only)
        run: docker build -t checkout-service:ci .
